name: onyx
version: 0.1.0
description: "Discord command handler based around functioning with Nyxx's Rest implementation."

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  nyxx: ^3.2.3

dev_dependencies:
  alfred: ^0.1.5+3
  cryptography: ^2.0.5
