name: onyx
version: 0.4.3
description: "A library focused on handling Interactions, Application Commands, and Message Components for Discord."

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  alfred: ^1.0.0
  cryptography: ^2.4.0
  http: ^0.13.5
