name: onyx
version: 0.3.0
description: "A library focused on handling Interactions, Application Commands, and Message Components for Discord."

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  alfred: ^0.1.7
  cryptography: ^2.0.5
  http: ^0.13.5
